# Action to deploy or stow a sail

uint8 target_sail   # enum
bool deploy         
bool stow
float32 sail_angle      # angle of the sail chord line measured from dead ahead that the sail should be when fully deployed
---
std_msgs/Header header 
sail_interfaces/SailPosition target_sail       # enum
bool stowed             # true if the sail is in the fully stowed position 
bool deployed           # true if the sail is in the fully deployed position
float32 mast_angle      # angle between the mast and the deck
float32 sail_angle      # angle of the sail chord line measured from dead ahead
---
std_msgs/Header header 
sail_interfaces/SailPosition target_sail       # enum
bool deploying
bool retracting
float32 mast_angle
float32 sail_angle
float32 sec_to_finish
float32 sec_from_start
float32 fraction_complete