# PID Debug Output 
# Includes all parameters used by the following libraries:
# https://github.com/br3ttb/Arduino-PID-Library/
# https://github.com/Tellicious/ArduPID-Library
# https://github.com/PowerBroker2/ArduPID

uint8 id            # loop identifier for nodes with multiple PID controllers
string label        # loop label for nodes with multiple PID controllers 
float32 input 
float32 output 
float32 setpoint 
float32 p 
float32 i 
float32 d 


